-- SIGO - schema PostgreSQL/Supabase
-- Execute este arquivo no SQL Editor do Supabase antes de iniciar o servidor Node.

create extension if not exists pgcrypto;

create table if not exists perfis (
  id integer generated by default as identity primary key,
  nome varchar(50) not null unique,
  descricao varchar(255),
  created_at timestamptz not null default now()
);

create table if not exists permissoes (
  id integer generated by default as identity primary key,
  chave varchar(80) not null unique,
  nome varchar(120) not null,
  categoria varchar(50) not null
);

create table if not exists perfil_permissoes (
  perfil_id integer not null references perfis(id) on delete cascade,
  permissao_id integer not null references permissoes(id) on delete cascade,
  primary key (perfil_id, permissao_id)
);

create table if not exists transportadoras (
  id integer generated by default as identity primary key,
  nome_fantasia varchar(100) not null,
  razao_social varchar(150),
  cnpj varchar(18) unique,
  email varchar(100),
  telefone varchar(20),
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists usuarios (
  id integer generated by default as identity primary key,
  nome varchar(100) not null,
  email varchar(100) not null unique,
  senha_hash text not null,
  perfil_id integer not null references perfis(id) on delete restrict,
  ativo boolean not null default true,
  is_despachante boolean not null default false,
  transportadora_id integer references transportadoras(id) on delete set null,
  token_recuperacao text,
  expiracao_token timestamptz,
  foto_url text,
  created_at timestamptz not null default now()
);

create table if not exists logs (
  id bigint generated by default as identity primary key,
  usuario_id integer references usuarios(id) on delete set null,
  acao varchar(100) not null,
  descricao text not null,
  ip_address varchar(45),
  created_at timestamptz not null default now()
);

create table if not exists solicitacoes_acesso (
  id integer generated by default as identity primary key,
  nome varchar(100) not null,
  email varchar(100) not null,
  senha_hash text not null,
  perfil_solicitado_id integer not null references perfis(id) on delete cascade,
  is_despachante boolean not null default false,
  transportadora_id integer references transportadoras(id) on delete set null,
  justificativa text not null,
  status varchar(20) not null default 'Pendente',
  created_at timestamptz not null default now(),
  constraint solicitacoes_status_check check (status in ('Pendente', 'Aprovada', 'Rejeitada'))
);

create table if not exists configuracoes (
  chave varchar(80) primary key,
  valor text not null,
  updated_at timestamptz not null default now()
);

create table if not exists romaneios (
  id bigint generated by default as identity primary key,
  usuario_id integer references usuarios(id) on delete set null,
  transportadora_id integer not null references transportadoras(id) on delete restrict,
  onda varchar(30) not null,
  vaga varchar(30) not null,
  gaiola varchar(30) not null,
  regiao varchar(100) not null,
  bairros_devolucao text,
  veiculo varchar(30),
  paradas integer not null default 0,
  placa varchar(15),
  rota varchar(30),
  data_romaneio date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists idx_romaneios_data on romaneios(data_romaneio);
create index if not exists idx_romaneios_placa_data on romaneios(placa, data_romaneio);
create index if not exists idx_romaneios_transportadora on romaneios(transportadora_id);

create table if not exists romaneio_logs (
  id bigint generated by default as identity primary key,
  romaneio_id bigint not null references romaneios(id) on delete cascade,
  usuario_id integer references usuarios(id) on delete set null,
  campo_alterado varchar(80) not null,
  valor_anterior text,
  valor_novo text,
  fora_do_horario boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists docas (
  id integer generated by default as identity primary key,
  nome varchar(30) not null unique,
  ativa boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists doca_operacoes (
  id bigint generated by default as identity primary key,
  doca_id integer references docas(id) on delete set null,
  romaneio_id bigint references romaneios(id) on delete set null,
  placa varchar(15) not null,
  transportadora_nome varchar(100),
  onda varchar(30),
  rota varchar(30),
  regiao varchar(100),
  bairros_devolucao text,
  status varchar(30) not null default 'aguardando_doca',
  posicao_fila integer not null default 0,
  entrada_cd_at timestamptz,
  carregando_at timestamptz,
  saida_cd_at timestamptz,
  tempo_total_min integer,
  tempo_carga_min integer,
  criado_por integer references usuarios(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint doca_operacoes_status_check check (status in ('aguardando_doca', 'na_fila', 'carregando', 'concluido'))
);

create index if not exists idx_doca_operacoes_ativas on doca_operacoes(placa, status);
create index if not exists idx_doca_operacoes_doca_fila on doca_operacoes(doca_id, status, posicao_fila);

create table if not exists motorista_reportes (
  id bigint generated by default as identity primary key,
  romaneio_id bigint references romaneios(id) on delete set null,
  placa varchar(15) not null,
  observacao text not null,
  foto1_url text,
  foto1_mime varchar(40),
  foto2_url text,
  foto2_mime varchar(40),
  foto3_url text,
  foto3_mime varchar(40),
  lido boolean not null default false,
  created_at timestamptz not null default now()
);

insert into perfis (id, nome, descricao) values
  (1, 'Administrador', 'Acesso total a todas as configuracoes e modulos do sistema'),
  (2, 'Operador de Expedicao', 'Gestao de Romaneios, Check-in, Check-out e Monitor de Docas'),
  (3, 'Motorista', 'Acesso simplificado ao aplicativo movel de motorista')
on conflict (id) do update set nome = excluded.nome, descricao = excluded.descricao;

select setval(pg_get_serial_sequence('perfis', 'id'), greatest((select max(id) from perfis), 1), true);

insert into permissoes (id, chave, nome, categoria) values
  (1, 'cadastrar_perfis', 'Cadastrar Perfis', 'Configuracoes'),
  (2, 'permissao_perfis', 'Gerenciar Permissoes de Perfis', 'Configuracoes'),
  (3, 'cadastrar_usuarios', 'Gerenciar Usuarios', 'Configuracoes'),
  (4, 'cadastrar_transportadoras', 'Gerenciar Transportadoras', 'Configuracoes'),
  (5, 'visualizar_logs', 'Visualizar Logs do Sistema', 'Configuracoes'),
  (6, 'acesso_expedicao', 'Acesso ao Modulo de Expedicao', 'Operacional'),
  (7, 'acesso_absenteismo', 'Acesso ao Modulo de Absenteismo', 'Operacional'),
  (8, 'acesso_horas_extras', 'Acesso ao Modulo de Horas Extras', 'Operacional'),
  (9, 'acesso_qualidade', 'Acesso ao Modulo de Qualidade', 'Operacional'),
  (10, 'acesso_romaneios', 'Acesso a Romaneios', 'Expedicao'),
  (11, 'acesso_checkin', 'Acesso ao Check-in', 'Expedicao'),
  (12, 'acesso_checkout', 'Acesso ao Check-out', 'Expedicao'),
  (13, 'acesso_monitor_docas', 'Acesso ao Monitor de Docas', 'Expedicao'),
  (14, 'acesso_app_motorista', 'Acesso ao App do Motorista', 'Expedicao')
on conflict (id) do update set chave = excluded.chave, nome = excluded.nome, categoria = excluded.categoria;

select setval(pg_get_serial_sequence('permissoes', 'id'), greatest((select max(id) from permissoes), 1), true);

insert into perfil_permissoes (perfil_id, permissao_id)
select 1, id from permissoes
on conflict do nothing;

insert into perfil_permissoes (perfil_id, permissao_id) values
  (2, 6), (2, 10), (2, 11), (2, 12), (2, 13)
on conflict do nothing;

insert into usuarios (id, nome, email, senha_hash, perfil_id, ativo)
values (1, 'Administrador', 'admin@sigo.com.br', crypt('admin', gen_salt('bf')), 1, true)
on conflict (id) do nothing;

select setval(pg_get_serial_sequence('usuarios', 'id'), greatest((select max(id) from usuarios), 1), true);

insert into configuracoes (chave, valor) values ('horario_corte', '18:00')
on conflict (chave) do nothing;

insert into docas (nome, ativa) values
  ('Doca 1', true),
  ('Doca 2', true),
  ('Doca 3', true),
  ('Doca 4', true)
on conflict (nome) do nothing;

insert into storage.buckets (id, name, public)
values ('sigo-uploads', 'sigo-uploads', true)
on conflict (id) do update set public = true;

drop policy if exists "SIGO public read uploads" on storage.objects;
create policy "SIGO public read uploads"
on storage.objects for select
using (bucket_id = 'sigo-uploads');
